name: Gerar APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Preparar, Assinar e Compilar APK
        run: |
          # Encontra a pasta exata do projeto Android e entra nela dinamicamente
          cd "$(dirname "$(find . -name "gradlew" | head -n 1)")"
          
          # Gera a chave de segurança de debug necessária para o Android aceitar a instalação
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          
          # Permissão e execução do build do Gradle
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Disponibilizar Instalador (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: "**/app/build/outputs/apk/debug/*.apk"
          retention-days: 14
